# RocketMQ配置示例
rocketmq:
  # 是否启用RocketMQ
  enabled: true
  
  # RocketMQ服务端点
  endpoints: localhost:8081
  
  # 生产者配置
  producer:
    # 生产者组
    group: platform-producer-group
    # 发送超时时间
    send-timeout: 3s
    # 最大尝试次数
    max-attempts: 3
    # 是否启用事务
    transaction-enabled: false
    # 压缩阈值（字节）
    compress-threshold: 4096
  
  # 消费者配置
  consumer:
    # 最大缓存消息数
    max-cached-message-count: 1000
    # 消费线程数
    consumption-thread-count: 20
    # 消费超时时间
    consume-timeout: 15s
    # 批量消费大小
    consume-batch-size: 1
    # 重试间隔
    retry-interval: 30s
    
    # 订单消费者配置
    order:
      group: order-consumer-group
      topic: order-topic
    
    # 用户消费者配置
    user:
      group: user-consumer-group
      topic: user-topic
    
    # 通知消费者配置
    notification:
      group: notification-consumer-group
      topic: notification-topic
      enabled: true
  
  # 消息存储配置
  message-store:
    # 是否启用消息存储
    enabled: true
    # 是否存储消息体
    store-body: true
    # 消息体最大长度（超过此长度将被截断）
    max-body-length: 65536
    # 清理保留天数
    retention-days: 30
    # 是否启用自动清理
    auto-clean: true
    # 清理定时表达式（每天凌晨2点执行）
    clean-cron: "0 0 2 * * ?"

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform_rocketmq?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      test-on-borrow: true
      
# 日志配置
logging:
  level:
    com.platform.rocketmq: DEBUG
    org.apache.rocketmq: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"