version: '3'

services:
  # 前端应用构建服务
  frontend-builder:
    image: node:18-alpine
    container_name: frontend-builder
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build"
    profiles: ["build"]

  # 前端应用部署
  frontend:
    image: nginx:latest
    container_name: platform-frontend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./config/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - platform_net
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    depends_on:
      - nginx

networks:
  platform_net:
    external: true
