spring:
  datasource:
    url: jdbc:mysql://mysql-host:3306/scheduler?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME:prod_user}
    password: ${MYSQL_PASSWORD:prod_password}
  data:
    redis:
      host: ${REDIS_HOST:redis-host}
      port: ${REDIS_PORT:6379}
      database: 0
      password: ${REDIS_PASSWORD:prod_password}
      timeout: 10000
      cluster:
        nodes: ${REDIS_CLUSTER_NODES:redis-node1:6379,redis-node2:6379,redis-node3:6379}

# 日志配置
logging:
  level:
    root: warn
    com.platform.scheduler: info
  file:
    name: /var/log/scheduler-service/scheduler-service.log
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 60

# 服务器配置
server:
  port: 8080
  tomcat:
    max-threads: 500
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 1000

# 调度器配置
scheduler:
  task:
    scan-rate: 3000  # 生产环境下扫描频率更高，单位毫秒
    max-parallel-tasks: 300  # 生产环境下最大并行任务数更高
  node:
    heartbeat-rate: 15000  # 生产环境下心跳频率，单位毫秒

# SpringDoc配置
springdoc:
  api-docs:
    enabled: false  # 生产环境下禁用API文档
