# 全局配置
global:
  scrape_interval: 15s # 默认抓取间隔
  evaluation_interval: 15s # 规则评估间隔

# 告警管理器配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  # Spring Boot应用监控
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['host.docker.internal:8080']

  # MySQL监控 (需要安装exporter)
  - job_name: 'mysql'
    static_configs:
    - targets: ['host.docker.internal:9104']

  # Redis监控 (需要安装exporter)
  - job_name: 'redis'
    static_configs:
    - targets: ['host.docker.internal:9121']

  # RabbitMQ监控
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['rabbitmq:15692']

  # Kafka监控 (需要安装JMX exporter)
  - job_name: 'kafka'
    static_configs:
    - targets: ['host.docker.internal:9308']

  # Node监控 (需要安装exporter)
  - job_name: 'node'
    static_configs:
    - targets: ['host.docker.internal:9100']

  # Nginx监控 (需要配置stub_status)
  - job_name: 'nginx'
    static_configs:
    - targets: ['host.docker.internal:9113']
