apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-dev
  labels:
    name: platform-dev
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform-test
  labels:
    name: platform-test
    environment: testing 