# Platform API 通用配置
# 适用于所有环境的API服务配置

spring:
  application:
    name: platform-api
    
  # Web配置
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    
  # JSON配置
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      
  # 国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
    
# 平台API通用配置
platform:
  api:
    # 基础配置
    name: Platform API Service
    description: 企业级数据平台核心API服务
    
    # 安全配置
    security:
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        max-age: 3600
        
    # 限流配置
    rate-limit:
      enabled: true
      permits-per-second: 100
      burst-capacity: 200
      
    # 缓存配置
    cache:
      enabled: true
      prefix: "platform:api:"
      default-ttl: 3600
      
    # 文件上传配置
    upload:
      max-file-size: 10MB
      max-request-size: 50MB
      temp-location: /tmp/uploads
      
    # API文档配置
    doc:
      enabled: true
      packages: com.platform.api.controller
      
    # 监控配置
    metrics:
      enabled: true
      export-to-prometheus: true
      
# 监控配置
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    tags:
      service: platform-api
      
# OpenAPI配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method 